### ISSUE TITLE
Accuracy of the Model

### ISSUE THREAD

**Issue by btomtom5** [junhwanjang/face_landmark_dnn#7]
Do you have a demo of model by any chance? I was having trouble getting the code to run. 

`OpenCV: Couldn't read video stream from file "samples/IU.avi"
Traceback (most recent call last):
  File "test_video.py", line 82, in <module>
    single_main()
  File "test_video.py", line 29, in single_main
    mark_detector = MarkDetector()
  File "/face_landmark_dnn/testing/mark_detector.py", line 22, in __init__
    self.face_detector = FaceDetector()
  File "ace_landmark_dnn/testing/mark_detector.py", line 162, in __init__
    self.face_net = cv2.dnn.readNetFromCaffe(dnn_proto_text, dnn_model)
cv2.error: OpenCV(3.4.4) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/Users/seerslab/projects/face_landmark_dnn/src/assets/deploy.prototxt" in function 'ReadProtoFromTextFile'`

**Comment by junhwanjang** [comment]
[mark_detector.py](https://github.com/junhwanjang/face_landmark_dnn/blob/master/testing/mark_detector.py)
Line 159,160: you need to change it as relative path in asset folder

**Comment by junhwanjang** [comment]
@btomtom5 I just changed it. Thanks:)

**Comment by sarratouil** [comment]
@junhwanjang  can I detect just the iris of eyes as you see ?
![iris](https://user-images.githubusercontent.com/34163796/56670545-50a9df80-66b3-11e9-90b6-0dc54057afe7.jpg)

**Comment by hao-qiang** [comment]
> @junhwanjang can I detect just the iris of eyes as you see ?
> ![iris](https://user-images.githubusercontent.com/34163796/56670545-50a9df80-66b3-11e9-90b6-0dc54057afe7.jpg)

Could you tell me where can I get the dataset as you show? Thanks a lot.
